source "amazon-ebs" "autogenerated_1" {
  ami_name      = "ale_basic_test"
  instance_type = "t2.micro"
  region        = "eu-west-1"
  source_ami    = "ami-063d4ab14480ac177"
  ssh_username  = "ec2-user"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

}
